{# TAS-280: Python Pydantic BaseModel generation from result_schema -#}
"""Generated by tasker-ctl generate types. Do not edit."""
from __future__ import annotations
{% if needs_any %}
from typing import Any, Optional
{%- else %}
from typing import Optional
{%- endif %}

from pydantic import BaseModel
{% for type_def in types %}

{% if type_def.description.is_some() -%}
class {{ type_def.name }}(BaseModel):
    """{{ type_def.description.as_deref().unwrap_or_default() }}"""
{%- else -%}
class {{ type_def.name }}(BaseModel):
{%- endif %}
{%- if type_def.fields.is_empty() %}
    pass
{%- else %}
{%- for field in type_def.fields %}
{%- if field.description.is_some() %}
    # {{ field.description.as_deref().unwrap_or_default() }}
{%- endif %}
{%- if field.field_type.is_string_enum() %}
    # Allowed values: {{ field.field_type.enum_values()|join(", ") }}
{%- endif %}
{%- if field.required %}
    {{ field.snake_name() }}: {{ field.field_type.python_type() }}
{%- else %}
    {{ field.snake_name() }}: Optional[{{ field.field_type.python_type() }}] = None
{%- endif %}
{%- endfor %}
{%- endif %}
{%- endfor %}
