{# Scaffold: Python tests with typed imports and typed mock data -#}
"""Generated by tasker-ctl generate scaffold. Tests use typed models."""

from .handlers import {% for handler in handlers %}{{ handler.snake_name() }}{% if !loop.last %}, {% endif %}{% endfor %}

{% if !import_types.is_empty() -%}
from .{{ types_module_name }} import {% for t in import_types %}{{ t }}{% if !loop.last %}, {% endif %}{% endfor %}

{% endif -%}
{% for handler in handlers %}

class Test{{ handler.pascal_name() }}:
{%- if handler.has_dependencies() %}
    def test_{{ handler.snake_name() }}_with_dependencies(self):
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
        mock_{{ dep.snake_param() }} = {{ type_name }}(
{%- for field in td.fields %}
            {{ field.name }}={{ field.field_type.python_stub_value() }},
{%- endfor %}
        )
{%- when None %}
        mock_{{ dep.snake_param() }} = {}
{%- endmatch %}
{%- when None %}
        mock_{{ dep.snake_param() }} = {}
{%- endmatch %}
{%- endfor %}
        # TODO: create mock context
        result = {{ handler.snake_name() }}(
{%- for dep in handler.dependencies %}
            {{ dep.snake_param() }}=mock_{{ dep.snake_param() }},
{%- endfor %}
            context=None,
        )
        assert result is not None
{%- else %}
    def test_{{ handler.snake_name() }}_returns_expected_shape(self):
        # TODO: create mock context
        result = {{ handler.snake_name() }}(context=None)
        assert result is not None
{%- endif %}
{%- match handler.result_type_name() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (_td) %}
        assert isinstance(result, {{ type_name }})
{%- when None %}
{%- endmatch %}
{%- when None %}
{%- endmatch %}
{%- endfor %}
