{# Scaffold: Ruby RSpec tests with typed mock data -#}
# frozen_string_literal: true

# Generated by tasker-ctl generate scaffold. Tests use generated types.

require "spec_helper"
require_relative '{{ types_module_name }}'
{% for handler in handlers %}

RSpec.describe "{{ handler.pascal_name() }}" do
{%- if handler.has_dependencies() %}
  it "processes with dependencies" do
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
    mock_{{ dep.snake_param() }} = {{ type_name }}.new(
{%- for field in td.fields %}
      {{ field.name }}: {{ field.field_type.ruby_stub_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
    )
{%- when None %}
    mock_{{ dep.snake_param() }} = {}
{%- endmatch %}
{%- when None %}
    mock_{{ dep.snake_param() }} = {}
{%- endmatch %}
{%- endfor %}
    # TODO: create mock context and invoke handler
    expect(true).to be true # placeholder
  end
{%- else %}
  it "returns expected result" do
    # TODO: create mock context and invoke handler
    expect(true).to be true # placeholder
  end
{%- endif %}
end
{%- endfor %}
