{# Scaffold: TypeScript tests with typed mock data -#}
/** Generated by tasker-ctl generate scaffold. Tests use generated types. */
import { describe, test, expect } from 'bun:test';
{% if !import_types.is_empty() -%}
import { {% for t in import_types %}{{ t }}{% if !loop.last %}, {% endif %}{% endfor %} } from './{{ types_module_name }}';
{% endif -%}
import { {% for handler in handlers %}{{ handler.pascal_name() }}{% if !loop.last %}, {% endif %}{% endfor %} } from './handlers';
{% for handler in handlers %}

describe('{{ handler.pascal_name() }}', () => {
{%- if handler.has_dependencies() %}
  test('processes with dependencies', async () => {
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
    const mock{{ dep.pascal_param() }}: {{ type_name }} = {
{%- for field in td.fields %}
      {{ field.name }}: {{ field.field_type.typescript_stub_value() }},
{%- endfor %}
    };
{%- when None %}
    const mock{{ dep.pascal_param() }} = {};
{%- endmatch %}
{%- when None %}
    const mock{{ dep.pascal_param() }} = {};
{%- endmatch %}
{%- endfor %}
    const mockContext = {};
    const result = await {{ handler.pascal_name() }}.handler({
{%- for dep in handler.dependencies %}
      {{ dep.camel_param() }}: mock{{ dep.pascal_param() }},
{%- endfor %}
      context: mockContext,
    });
    expect(result).toBeDefined();
  });
{%- else %}
  test('returns expected result', async () => {
    const mockContext = {};
    const result = await {{ handler.pascal_name() }}.handler({ context: mockContext });
    expect(result).toBeDefined();
  });
{%- endif %}
});
{%- endfor %}
