{# Scaffold: Rust tests with typed mock data -#}
/// Generated by tasker-ctl generate scaffold. Tests use generated types.

#[cfg(test)]
mod tests {
    use serde_json::json;
{% if !import_types.is_empty() %}
    use super::models::{%raw%}{{%endraw%}{% for t in import_types %}{{ t }}{% if !loop.last %}, {% endif %}{% endfor %}{%raw%}}{%endraw%};
{% endif %}
{% for handler in handlers %}

    #[tokio::test]
    async fn test_{{ handler.snake_name() }}() {
{%- if handler.has_dependencies() %}
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
        let _mock_{{ dep.snake_param() }} = {{ type_name }} {
{%- for field in td.fields %}
            {{ field.snake_name() }}: {{ field.field_type.rust_stub_value() }},
{%- endfor %}
        };
{%- when None %}
        let _mock_{{ dep.snake_param() }} = json!({});
{%- endmatch %}
{%- when None %}
        let _mock_{{ dep.snake_param() }} = json!({});
{%- endmatch %}
{%- endfor %}
{%- endif %}
        // TODO: create test step_data and invoke handler
        assert!(true); // placeholder
    }
{%- endfor %}
}
