{# Scaffold: TypeScript vitest tests with typed mock data -#}
/** Generated by tasker-ctl generate scaffold. Tests use generated types. */
import { describe, it, expect } from 'vitest';
{% if !import_types.is_empty() -%}
import { {% for t in import_types %}{{ t }}{% if !loop.last %}, {% endif %}{% endfor %} } from './{{ types_module_name }}';
{% endif -%}
{% for handler in handlers %}

describe('{{ handler.pascal_name() }}', () => {
{%- if handler.has_dependencies() %}
  it('processes with dependencies', async () => {
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
    const mock{{ dep.pascal_param() }}: {{ type_name }} = {
{%- for field in td.fields %}
      {{ field.name }}: {{ field.field_type.typescript_stub_value() }},
{%- endfor %}
    };
{%- when None %}
    const mock{{ dep.pascal_param() }} = {};
{%- endmatch %}
{%- when None %}
    const mock{{ dep.pascal_param() }} = {};
{%- endmatch %}
{%- endfor %}
    // TODO: create mock context and invoke handler
    expect(true).toBe(true); // placeholder
  });
{%- else %}
  it('returns expected result', async () => {
    // TODO: create mock context and invoke handler
    expect(true).toBe(true); // placeholder
  });
{%- endif %}
});
{%- endfor %}
