{# Scaffold: Rust tests that invoke plain function handlers -#}
/// Generated by tasker-ctl generate scaffold. Tests invoke handlers directly.

#[cfg(test)]
mod tests {
    use serde_json::json;
    use std::collections::HashMap;
{% if !import_types.is_empty() %}
    use super::models::{
{%- for t in import_types %}
        {{ t }},
{%- endfor %}
    };
{%- endif %}
    use super::handlers;
{% for handler in handlers %}

    #[test]
    fn test_{{ handler.snake_name() }}() {
{%- if handler.has_dependencies() %}
        let context = json!({});
        let mut deps = HashMap::new();
{%- for dep in handler.dependencies %}
{%- match dep.result_type.as_ref() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
        deps.insert("{{ dep.step_name }}".to_string(), json!({
{%- for field in td.fields %}
            "{{ field.name }}": {{ field.field_type.json_stub_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
        }));
{%- when None %}
        deps.insert("{{ dep.step_name }}".to_string(), json!({}));
{%- endmatch %}
{%- when None %}
        deps.insert("{{ dep.step_name }}".to_string(), json!({}));
{%- endmatch %}
{%- endfor %}
        let result = handlers::{{ handler.snake_name() }}(&context, &deps);
        assert!(result.is_ok(), "handler should succeed: {:?}", result.err());
{%- match handler.result_type_name() %}
{%- when Some with (type_name) %}
        let value = result.unwrap();
        let _typed: {{ type_name }} = serde_json::from_value(value).expect("result should deserialize to {{ type_name }}");
{%- when None %}
{%- endmatch %}
{%- else %}
        let context = json!({});
        let deps = HashMap::new();
        let result = handlers::{{ handler.snake_name() }}(&context, &deps);
        assert!(result.is_ok(), "handler should succeed: {:?}", result.err());
{%- match handler.result_type_name() %}
{%- when Some with (type_name) %}
        let value = result.unwrap();
        let _typed: {{ type_name }} = serde_json::from_value(value).expect("result should deserialize to {{ type_name }}");
{%- when None %}
{%- endmatch %}
{%- endif %}
    }
{%- endfor %}
}
