/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Configuration for bootstrapping the worker. */
export interface BootstrapConfig {
  namespace?: string
  configPath?: string
}

/** Result of bootstrapping the worker. */
export interface BootstrapResult {
  success: boolean
  status: string
  message: string
  workerId?: string
}

/** Bootstrap the worker system. */
export declare function bootstrapWorker(config?: BootstrapConfig | undefined | null): BootstrapResult

/** Yield a checkpoint for batch processing (TAS-125). */
export declare function checkpointYieldStepEvent(eventId: string, checkpoint: NapiCheckpointYieldData): boolean

/** Check for and log starvation warnings. */
export declare function checkStarvationWarnings(): void

/** Cleanup timed-out events. */
export declare function cleanupTimeouts(): void

/** Cancel a task by UUID. */
export declare function clientCancelTask(taskUuid: string): NapiClientResult

/**
 * Create a task via the orchestration API.
 *
 * Native object crossing — no JSON serialization, no TAS-283 trailing input.
 */
export declare function clientCreateTask(request: NapiTaskRequest): NapiClientResult

/** Get a specific workflow step. */
export declare function clientGetStep(taskUuid: string, stepUuid: string): NapiClientResult

/** Get audit history for a workflow step. */
export declare function clientGetStepAuditHistory(taskUuid: string, stepUuid: string): NapiClientResult

/** Get a task by UUID. */
export declare function clientGetTask(taskUuid: string): NapiClientResult

/** Health check against the orchestration API. */
export declare function clientHealthCheck(): NapiClientResult

/** List tasks with optional filters. */
export declare function clientListTasks(params: NapiListTasksParams): NapiClientResult

/** List steps for a task. */
export declare function clientListTaskSteps(taskUuid: string): NapiClientResult

/**
 * Complete a step event with the handler's result.
 *
 * Accepts a serde_json::Value (JavaScript object) and deserializes it into
 * a StepExecutionResult. This mirrors the Python (depythonize) and Ruby
 * (serde_magnus::deserialize) approaches — the language side builds a full
 * serde-compatible object with snake_case keys.
 */
export declare function completeStepEvent(eventId: string, result: any): boolean

/** Get FFI dispatch metrics. */
export declare function getFfiDispatchMetrics(): NapiDispatchMetrics

/** Returns the Rust library version for debugging. */
export declare function getRustVersion(): string

/** Returns the version of the tasker-ts package. */
export declare function getVersion(): string

/** Get worker status. */
export declare function getWorkerStatus(): WorkerStatus

/** Simple health check to verify the FFI layer is functional. */
export declare function healthCheck(): boolean

/** Check if the worker is currently running. */
export declare function isWorkerRunning(): boolean

/** Log a debug message with optional structured fields. */
export declare function logDebug(message: string, fields?: Record<string, any> | undefined | null): void

/** Log an error message with optional structured fields. */
export declare function logError(message: string, fields?: Record<string, any> | undefined | null): void

/** Log an info message with optional structured fields. */
export declare function logInfo(message: string, fields?: Record<string, any> | undefined | null): void

/** Log a trace message with optional structured fields. */
export declare function logTrace(message: string, fields?: Record<string, any> | undefined | null): void

/** Log a warning message with optional structured fields. */
export declare function logWarn(message: string, fields?: Record<string, any> | undefined | null): void

/** Checkpoint yield data for batch processing (TAS-125). */
export interface NapiCheckpointYieldData {
  stepUuid: string
  cursor: any
  itemsProcessed: number
  accumulatedResults?: any
}

/**
 * Client operation result.
 *
 * Maintains the existing TypeScript API surface with success/data/error envelope.
 */
export interface NapiClientResult {
  success: boolean
  data?: any
  error?: string
  recoverable?: boolean
}

export interface NapiDependencyResult {
  stepUuid: string
  success: boolean
  result: any
  status: string
  errorMessage?: string
  errorType?: string
  errorRetryable?: boolean
}

/** FFI dispatch metrics. */
export interface NapiDispatchMetrics {
  pendingCount: number
  starvationDetected: boolean
  starvingEventCount: number
  oldestPendingAgeMs?: number
  newestPendingAgeMs?: number
  oldestEventId?: string
}

/** Domain event from in-process event bus (fast path). */
export interface NapiDomainEvent {
  eventId: string
  eventName: string
  eventVersion: string
  metadata: NapiDomainEventMetadata
  payload: any
}

/** Metadata attached to domain events. */
export interface NapiDomainEventMetadata {
  taskUuid: string
  stepUuid?: string
  stepName?: string
  namespace: string
  correlationId: string
  firedAt: string
  firedBy?: string
}

/** Parameters for listing tasks. */
export interface NapiListTasksParams {
  limit?: number
  offset?: number
  namespace?: string
  status?: string
}

export interface NapiStepDefinition {
  name: string
  description?: string
  handlerCallable: string
  handlerMethod?: string
  handlerResolver?: string
  handlerInitialization: any
  systemDependency?: string
  dependencies: Array<string>
  timeoutSeconds?: number
  retryRetryable: boolean
  retryMaxAttempts: number
  retryBackoff: string
  retryBackoffBaseMs?: number
  retryMaxBackoffMs?: number
}

/** A step event dispatched to the TypeScript handler. */
export interface NapiStepEvent {
  eventId: string
  taskUuid: string
  stepUuid: string
  correlationId: string
  traceId?: string
  spanId?: string
  taskCorrelationId: string
  parentCorrelationId?: string
  task: NapiTaskInfo
  workflowStep: NapiWorkflowStep
  stepDefinition: NapiStepDefinition
  dependencyResults: Record<string, NapiDependencyResult>
}

export interface NapiTaskInfo {
  taskUuid: string
  namedTaskUuid: string
  name: string
  namespace: string
  version: string
  context?: any
  correlationId: string
  parentCorrelationId?: string
  complete: boolean
  priority: number
  initiator?: string
  sourceSystem?: string
  reason?: string
  tags?: any
  identityHash: string
  createdAt: string
  updatedAt: string
  requestedAt: string
}

/**
 * Task creation request — crosses FFI as native JS object.
 *
 * In koffi, this was serialized to JSON and parsed with
 * `serde_json::Deserializer::from_str` to tolerate trailing bytes.
 * In napi-rs, no serialization needed. No trailing bytes. No TAS-283.
 */
export interface NapiTaskRequest {
  name: string
  namespace: string
  version: string
  /** Native JS object — napi-rs handles this via serde-json feature */
  context: any
  initiator: string
  sourceSystem: string
  reason: string
  tags?: Array<string>
  priority?: number
  correlationId?: string
  parentCorrelationId?: string
  idempotencyKey?: string
}

export interface NapiWorkflowStep {
  workflowStepUuid: string
  taskUuid: string
  namedStepUuid: string
  name: string
  templateStepName: string
  retryable: boolean
  maxAttempts: number
  attempts: number
  inProcess: boolean
  processed: boolean
  inputs?: any
  results?: any
  backoffRequestSeconds?: number
  processedAt?: string
  lastAttemptedAt?: string
  createdAt: string
  updatedAt: string
  checkpoint?: any
}

/** Poll for in-process domain events (fast path). */
export declare function pollInProcessEvents(): NapiDomainEvent | null

/** Poll for a step event to dispatch. */
export declare function pollStepEvents(): NapiStepEvent | null

/** Stop the worker system. */
export declare function stopWorker(): WorkerStatus

/** Transition the worker to graceful shutdown mode. */
export declare function transitionToGracefulShutdown(): WorkerStatus

/** Worker status information. */
export interface WorkerStatus {
  success: boolean
  running: boolean
  workerId?: string
  status?: string
  environment?: string
}
