{# TAS-280: Ruby RSpec test scaffold generation from task template -#}
# frozen_string_literal: true

# Generated by tasker-ctl generate handler --with-tests. Customize to test your handlers.

require "spec_helper"
{% for handler in handlers %}

RSpec.describe "{{ handler.pascal_name() }}" do
{%- if handler.has_dependencies() %}
  it "processes with dependencies" do
{%- for dep in handler.dependencies %}
{%- if dep.result_type.is_some() %}
    mock_{{ dep.snake_param() }} = {
{%- for field in dep.stub_fields %}
      {{ field.name }}: {{ field.ruby_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
    }
{%- else %}
    mock_{{ dep.snake_param() }} = {}
{%- endif %}
{%- endfor %}
    # TODO: create mock context and invoke handler
    expect(true).to be true # placeholder
  end
{%- else %}
  it "returns expected result" do
    # TODO: create mock context and invoke handler
    expect(true).to be true # placeholder
  end
{%- endif %}
end
{%- endfor %}
