{# TAS-280: Ruby handler scaffold generation from task template -#}
# frozen_string_literal: true

# Generated by tasker-ctl generate handler. Customize to implement your logic.

include TaskerCore::StepHandler::Functional
{% for handler in handlers %}

{{ handler.pascal_name() }} = step_handler(
  '{{ handler.callable }}'{% if handler.has_dependencies() %},
  depends_on: {
{%- for dep in handler.dependencies %}
    {{ dep.snake_param() }}: '{{ dep.step_name }}'{% if !loop.last %},{% endif %}
{%- endfor %}
  }
{%- endif %}

) do |{% if handler.has_dependencies() %}{% for dep in handler.dependencies %}{{ dep.snake_param() }}:, {% endfor %}{% endif %}context:|
{%- for dep in handler.dependencies %}
  # {{ dep.snake_param() }}: {{ dep.type_comment() }}
{%- endfor %}
  # TODO: implement handler logic
  TaskerCore::Types::StepHandlerCallResult.success(
{%- if !handler.stub_fields.is_empty() %}
    result: {
{%- for field in handler.stub_fields %}
      {{ field.name }}: {{ field.ruby_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
    }
{%- else %}
    result: {}
{%- endif %}
  )
end
{%- endfor %}
