{# TAS-280: Rust handler scaffold generation from task template -#}
//! Generated by tasker-ctl generate handler. Customize to implement your logic.

use serde_json::Value;
use std::collections::HashMap;
{% for handler in handlers %}

{% if handler.description.is_some() -%}
/// {{ handler.description.as_deref().unwrap_or_default() }}
{% endif -%}
pub fn {{ handler.snake_name() }}({% if handler.has_dependencies() %}_context{% else %}context{% endif %}: &Value, {% if handler.has_dependencies() %}dependency_results{% else %}_dependency_results{% endif %}: &HashMap<String, Value>) -> Result<Value, String> {
{%- for dep in handler.dependencies %}
    // Dependency: {{ dep.step_name }} — {{ dep.type_comment() }}
{%- endfor %}
    // TODO: implement handler logic
{%- if !handler.stub_fields.is_empty() %}
    let result = serde_json::json!({
{%- for field in handler.stub_fields %}
        "{{ field.name }}": {{ field.json_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
    });
    Ok(result)
{%- else %}
    Ok(serde_json::json!({}))
{%- endif %}
}
{%- endfor %}
