{# Scaffold: Ruby handlers with type requires and typed return values -#}
# frozen_string_literal: true

# Generated by tasker-ctl generate scaffold. Handlers use generated types.

require_relative '{{ types_module_name }}'
include TaskerCore::StepHandler::Functional
{% for handler in handlers %}

{{ handler.pascal_name() }} = step_handler(
  '{{ handler.callable }}'{% if handler.has_dependencies() %},
  depends_on: {
{%- for dep in handler.dependencies %}
    {{ dep.snake_param() }}: '{{ dep.step_name }}'{% if !loop.last %},{% endif %}
{%- endfor %}
  }
{%- endif %}

) do |{% if handler.has_dependencies() %}{% for dep in handler.dependencies %}{{ dep.snake_param() }}:, {% endfor %}{% endif %}context:|
{%- for dep in handler.dependencies %}
  # {{ dep.snake_param() }}: {{ dep.type_comment() }}
{%- endfor %}
  # TODO: implement handler logic
  TaskerCore::Types::StepHandlerCallResult.success(
{%- match handler.result_type_name() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
    result: {{ type_name }}.new(
{%- for field in td.fields %}
      {{ field.name }}: {{ field.field_type.ruby_stub_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
    )
{%- when None %}
    result: {}
{%- endmatch %}
{%- when None %}
    result: {}
{%- endmatch %}
  )
end
{%- endfor %}
