{# TAS-280: TypeScript Zod schema generation from result_schema -#}
/** Generated by tasker-ctl generate types. Do not edit. */
import { z } from 'zod';
{% for type_def in types %}

{% if type_def.description.is_some() -%}
/** {{ type_def.description.as_deref().unwrap_or_default() }} */
{% endif -%}
export const {{ type_def.name }}Schema = z.object({
{%- for field in type_def.fields %}
{%- if !field.required %}
  {{ field.name }}: {{ field.field_type.zod_type() }}.optional(),
{%- else %}
  {{ field.name }}: {{ field.field_type.zod_type() }},
{%- endif %}
{%- endfor %}
}).passthrough();

export type {{ type_def.name }} = z.infer<typeof {{ type_def.name }}Schema>;
{%- endfor %}
