//! Ruby Dry::Struct code generation.

use askama::Template;

use super::schema::TypeDef;
use super::CodegenError;

#[derive(Template, Debug)]
#[template(path = "codegen/ruby_structs.rb")]
struct RubyTemplate<'a> {
    types: &'a [TypeDef],
}

/// Render Ruby Dry::Struct classes from type definitions.
pub fn render(types: &[TypeDef]) -> Result<String, CodegenError> {
    let template = RubyTemplate { types };
    template
        .render()
        .map_err(|e| CodegenError::Rendering(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::schema::{FieldDef, FieldType};

    #[test]
    fn test_ruby_flat_types() {
        let types = vec![TypeDef {
            name: "ValidateOrderResult".to_string(),
            description: Some("Order validation".to_string()),
            fields: vec![
                FieldDef {
                    name: "validated".to_string(),
                    field_type: FieldType::Boolean,
                    required: true,
                    description: None,
                },
                FieldDef {
                    name: "order_total".to_string(),
                    field_type: FieldType::Number,
                    required: true,
                    description: None,
                },
                FieldDef {
                    name: "notes".to_string(),
                    field_type: FieldType::String,
                    required: false,
                    description: None,
                },
            ],
        }];

        let output = render(&types).unwrap();
        assert!(output.contains("class ValidateOrderResult < Dry::Struct"));
        assert!(output.contains("attribute :validated, Types::Strict::Bool"));
        assert!(output.contains("attribute :order_total, Types::Strict::Float"));
        assert!(output
            .contains("attribute :notes, Types::Strict::String.optional.meta(omittable: true)"));
    }

    #[test]
    fn test_ruby_empty_types() {
        let output = render(&[]).unwrap();
        assert!(output.contains("Generated by tasker-ctl"));
        assert!(!output.contains("class "));
    }
}
