//! TypeScript interface code generation.
//!
//! Retained for potential `--format interfaces` option. The default TypeScript
//! type output now uses Zod schemas via `typescript_zod` module.

use askama::Template;

use super::schema::TypeDef;
use super::CodegenError;

#[derive(Template, Debug)]
#[template(path = "codegen/typescript_interfaces.ts")]
struct TypeScriptTemplate<'a> {
    types: &'a [TypeDef],
}

/// Render TypeScript interfaces from type definitions.
#[expect(dead_code, reason = "retained for future --format interfaces option")]
pub fn render(types: &[TypeDef]) -> Result<String, CodegenError> {
    let template = TypeScriptTemplate { types };
    template
        .render()
        .map_err(|e| CodegenError::Rendering(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::schema::{FieldDef, FieldType};

    #[test]
    fn test_typescript_flat_types() {
        let types = vec![TypeDef {
            name: "ValidateOrderResult".to_string(),
            description: Some("Order validation".to_string()),
            fields: vec![
                FieldDef {
                    name: "validated".to_string(),
                    field_type: FieldType::Boolean,
                    required: true,
                    description: None,
                },
                FieldDef {
                    name: "order_total".to_string(),
                    field_type: FieldType::Number,
                    required: true,
                    description: None,
                },
                FieldDef {
                    name: "notes".to_string(),
                    field_type: FieldType::String,
                    required: false,
                    description: None,
                },
            ],
        }];

        let output = render(&types).unwrap();
        assert!(output.contains("export interface ValidateOrderResult {"));
        assert!(output.contains("validated: boolean;"));
        assert!(output.contains("order_total: number;"));
        assert!(output.contains("notes?: string;"));
    }

    #[test]
    fn test_typescript_empty_types() {
        let output = render(&[]).unwrap();
        assert!(output.contains("Generated by tasker-ctl"));
        assert!(!output.contains("export interface"));
    }
}
