{# TAS-280: Python test scaffold generation from task template -#}
"""Generated by tasker-ctl generate handler --with-tests. Customize to test your handlers."""
import pytest

from .handlers import {% for handler in handlers %}{{ handler.snake_name() }}{% if !loop.last %}, {% endif %}{% endfor %}

{% for handler in handlers %}

class Test{{ handler.pascal_name() }}:
{%- if handler.has_dependencies() %}
    def test_{{ handler.snake_name() }}_with_dependencies(self):
{%- for dep in handler.dependencies %}
{%- if dep.result_type.is_some() %}
        mock_{{ dep.snake_param() }} = {
{%- for field in handler.stub_fields %}
            "{{ field.name }}": {{ field.python_value() }},
{%- endfor %}
        }
{%- else %}
        mock_{{ dep.snake_param() }} = {}
{%- endif %}
{%- endfor %}
        # TODO: create mock context
        result = {{ handler.snake_name() }}(
{%- for dep in handler.dependencies %}
            {{ dep.snake_param() }}=mock_{{ dep.snake_param() }},
{%- endfor %}
            context=None,
        )
        assert result is not None
{%- else %}
    def test_{{ handler.snake_name() }}_returns_expected_shape(self):
        # TODO: create mock context
        result = {{ handler.snake_name() }}(context=None)
        assert result is not None
{%- endif %}
{%- if handler.has_result_schema %}
{%- for field in handler.stub_fields %}
        assert "{{ field.name }}" in result
{%- endfor %}
{%- endif %}
{%- endfor %}
