{# TAS-280: Python handler scaffold generation from task template -#}
"""Generated by tasker-ctl generate handler. Customize to implement your logic."""
from tasker_core.step_handler.functional import step_handler, depends_on
{% for handler in handlers %}

{% if handler.has_dependencies() -%}
@step_handler("{{ handler.callable }}")
{%- for dep in handler.dependencies %}
@depends_on({{ dep.snake_param() }}="{{ dep.step_name }}")
{%- endfor %}
def {{ handler.snake_name() }}(
    {%- for dep in handler.dependencies %}{{ dep.snake_param() }}, {% endfor %}context):
{%- else -%}
@step_handler("{{ handler.callable }}")
def {{ handler.snake_name() }}(context):
{%- endif %}
{% if handler.description.is_some() %}    """{{ handler.description.as_deref().unwrap_or_default() }}"""{% endif %}
{%- for dep in handler.dependencies %}
    # {{ dep.snake_param() }}: {{ dep.type_comment() }}
{%- endfor %}
    # TODO: implement handler logic
{%- if !handler.stub_fields.is_empty() %}
    return {
{%- for field in handler.stub_fields %}
        "{{ field.name }}": {{ field.python_value() }},
{%- endfor %}
    }
{%- else %}
    return {}
{%- endif %}
{%- endfor %}
