{# TAS-280: Ruby Dry::Struct generation from result_schema -#}
# frozen_string_literal: true

# Generated by tasker-ctl generate types. Do not edit.

require "dry-struct"

module Types
  include Dry.Types()
end
{% for type_def in types %}

{% if type_def.description.is_some() -%}
# {{ type_def.description.as_deref().unwrap_or_default() }}
{% endif -%}
class {{ type_def.name }} < Dry::Struct
{%- for field in type_def.fields %}
{%- if field.required %}
  attribute :{{ field.snake_name() }}, {{ field.field_type.ruby_type() }}
{%- else %}
  attribute :{{ field.snake_name() }}, {{ field.field_type.ruby_type() }}.optional.meta(omittable: true)
{%- endif %}
{%- endfor %}
end
{%- endfor %}
