{# TAS-280: Rust test scaffold generation from task template -#}
/// Generated by tasker-ctl generate handler --with-tests. Customize to test your handlers.

#[cfg(test)]
mod tests {
    use serde_json::json;
{% for handler in handlers %}

    #[tokio::test]
    async fn test_{{ handler.snake_name() }}() {
{%- if handler.has_dependencies() %}
{%- for dep in handler.dependencies %}
{%- if dep.result_type.is_some() %}
        let _mock_{{ dep.snake_param() }} = json!({
{%- for field in dep.stub_fields %}
            "{{ field.name }}": {{ field.json_value() }}{% if !loop.last %},{% endif %}
{%- endfor %}
        });
{%- else %}
        let _mock_{{ dep.snake_param() }} = json!({});
{%- endif %}
{%- endfor %}
{%- endif %}
        // TODO: create test step_data and invoke handler
        assert!(true); // placeholder
    }
{%- endfor %}
}
