{# TAS-280: Rust struct generation from result_schema -#}
//! Generated by tasker-ctl generate types. Do not edit.

use serde::{Deserialize, Serialize};
{% if needs_json_value -%}
use serde_json;
{% endif -%}
{% if needs_hashmap -%}
use std::collections::HashMap;
{% endif %}
{%- for type_def in types %}

{% if type_def.description.is_some() -%}
/// {{ type_def.description.as_deref().unwrap_or_default() }}
{% endif -%}
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct {{ type_def.name }} {
{%- for field in type_def.fields %}
{%- if field.field_type.is_string_enum() %}
    /// Allowed values: {{ field.field_type.enum_values()|join(", ") }}
{%- endif %}
{%- if field.is_rust_keyword() %}
    #[serde(rename = "{{ field.snake_name() }}")]
{%- endif %}
{%- if !field.required %}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub {{ field.rust_name() }}: Option<{{ field.field_type.rust_type() }}>,
{%- else %}
    pub {{ field.rust_name() }}: {{ field.field_type.rust_type() }},
{%- endif %}
{%- endfor %}
}
{%- endfor %}
