{# TAS-280: TypeScript handler scaffold generation from task template -#}
/** Generated by tasker-ctl generate handler. Customize to implement your logic. */
import { defineHandler } from 'tasker-worker';
{% for handler in handlers %}

export const {{ handler.pascal_name() }} = defineHandler(
  '{{ handler.callable }}',
{%- if handler.has_dependencies() %}
  {
    depends: {
{%- for dep in handler.dependencies %}
      {{ dep.camel_param() }}: '{{ dep.step_name }}'{% if !loop.last %},{% endif %}
{%- endfor %}
    },
  },
  async ({ {% for dep in handler.dependencies %}{{ dep.camel_param() }}, {% endfor %}context }) => {
{%- else %}
  {},
  async ({ context }) => {
{%- endif %}
{%- for dep in handler.dependencies %}
    // {{ dep.camel_param() }}: {{ dep.type_comment() }}
{%- endfor %}
    // TODO: implement handler logic
{%- if !handler.stub_fields.is_empty() %}
    return {
{%- for field in handler.stub_fields %}
      {{ field.name }}: {{ field.typescript_value() }},
{%- endfor %}
    };
{%- else %}
    return {};
{%- endif %}
  }
);
{%- endfor %}
