{# TAS-280: TypeScript interface generation from result_schema #}
/** Generated by tasker-ctl generate types. Do not edit. */
{% for type_def in types %}

{% if type_def.description.is_some() %}
/** {{ type_def.description.as_deref().unwrap_or_default() }} */
{% endif %}
export interface {{ type_def.name }} {
{% for field in type_def.fields %}
{% if !field.required %}
  {{ field.name }}?: {{ field.field_type.typescript_type() }};
{% else %}
  {{ field.name }}: {{ field.field_type.typescript_type() }};
{% endif %}
{% endfor %}
}
{% endfor %}
