//! Integration tests for `tasker-ctl generate handler` (TAS-280 Phase 2)
//!
//! Tests the full CLI pipeline: YAML parsing → handler extraction → scaffold generation.
//! Uses the codegen_test_template.yaml fixture.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Get the path to the compiled tasker-ctl binary.
fn tasker_ctl_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_tasker-ctl"))
}

/// Path to the codegen test fixture.
fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/fixtures/task_templates/codegen_test_template.yaml")
}

/// Run `tasker-ctl generate handler` with given language and optional extra args.
fn generate_handler(language: &str, extra_args: &[&str]) -> std::process::Output {
    let mut args = vec!["generate", "handler", "--template"];
    let fixture = fixture_path();
    let fixture_str = fixture.to_str().unwrap();
    args.push(fixture_str);
    args.push("--language");
    args.push(language);
    args.extend_from_slice(extra_args);

    Command::new(tasker_ctl_bin())
        .args(&args)
        .output()
        .expect("Failed to execute tasker-ctl")
}

// ── Python ──────────────────────────────────────────────────────────

#[test]
fn test_generate_python_handlers() {
    let output = generate_handler("python", &[]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Header
    assert!(stdout.contains("Generated by tasker-ctl generate handler"));
    assert!(stdout.contains("from tasker_core.step_handler.functional import"));

    // validate_order — no deps
    assert!(stdout.contains("@step_handler(\"codegen_tests.validate_order\")"));
    assert!(stdout.contains("def validate_order(context):"));

    // enrich_order — typed dependency on validate_order
    assert!(stdout.contains("@depends_on(validate_order_result=\"validate_order\")"));
    assert!(stdout.contains("def enrich_order(validate_order_result, context):"));

    // process_payment — untyped (no result_schema)
    assert!(stdout.contains("def process_payment("));
    assert!(!stdout.contains("ProcessPayment")); // no type generated

    // generate_report — multiple deps
    assert!(stdout.contains("def generate_report("));
}

// ── Ruby ────────────────────────────────────────────────────────────

#[test]
fn test_generate_ruby_handlers() {
    let output = generate_handler("ruby", &[]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    assert!(stdout.contains("ValidateOrderHandler = step_handler("));
    assert!(stdout.contains("EnrichOrderHandler = step_handler("));
    assert!(stdout.contains("depends_on: {"));
    assert!(stdout.contains("validate_order_result: 'validate_order'"));
}

// ── TypeScript ──────────────────────────────────────────────────────

#[test]
fn test_generate_typescript_handlers() {
    let output = generate_handler("typescript", &[]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    assert!(stdout.contains("export const ValidateOrderHandler = defineHandler("));
    assert!(stdout.contains("export const EnrichOrderHandler = defineHandler("));
    assert!(stdout.contains("validateOrderResult: 'validate_order'"));
}

// ── Rust ────────────────────────────────────────────────────────────

#[test]
fn test_generate_rust_handlers() {
    let output = generate_handler("rust", &[]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Plain function pattern (Pattern B)
    assert!(stdout.contains("pub fn validate_order("));
    assert!(stdout.contains("pub fn enrich_order("));
}

// ── Step filter ─────────────────────────────────────────────────────

#[test]
fn test_generate_handler_step_filter() {
    let output = generate_handler("python", &["--step", "enrich_order"]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Only enrich_order
    assert!(stdout.contains("def enrich_order("));
    assert!(!stdout.contains("def validate_order("));
    assert!(!stdout.contains("def process_payment("));
}

// ── With tests ──────────────────────────────────────────────────────

#[test]
fn test_generate_handler_with_tests() {
    let output = generate_handler("python", &["--with-tests"]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Handler output
    assert!(stdout.contains("@step_handler(\"codegen_tests.validate_order\")"));

    // Test output
    assert!(stdout.contains("class TestValidateOrderHandler:"));
    assert!(stdout.contains("class TestEnrichOrderHandler:"));
}

// ── Language aliases ────────────────────────────────────────────────

#[test]
fn test_generate_handler_language_aliases() {
    for (alias, expected) in [
        ("py", "def validate_order("),
        ("rb", "ValidateOrderHandler = step_handler("),
        ("ts", "export const ValidateOrderHandler = defineHandler("),
        ("rs", "pub fn validate_order("),
    ] {
        let output = generate_handler(alias, &["--step", "validate_order"]);
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            output.status.success(),
            "alias '{}' failed: {}",
            alias,
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            stdout.contains(expected),
            "alias '{}' output missing '{}' in:\n{}",
            alias,
            expected,
            stdout
        );
    }
}

// ── Error cases ─────────────────────────────────────────────────────

#[test]
fn test_generate_handler_file_not_found() {
    let output = Command::new(tasker_ctl_bin())
        .args([
            "generate",
            "handler",
            "--template",
            "/nonexistent/template.yaml",
            "--language",
            "python",
        ])
        .output()
        .expect("Failed to execute tasker-ctl");

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Failed to read template file"));
}

#[test]
fn test_generate_handler_unsupported_language() {
    let output = Command::new(tasker_ctl_bin())
        .args([
            "generate",
            "handler",
            "--template",
            fixture_path().to_str().unwrap(),
            "--language",
            "java",
        ])
        .output()
        .expect("Failed to execute tasker-ctl");

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unsupported language"));
}

// ── Output to file ──────────────────────────────────────────────────

#[test]
fn test_generate_handler_output_to_file() {
    let dir = tempfile::tempdir().unwrap();
    let output_path = dir.path().join("generated_handlers.py");

    let output = Command::new(tasker_ctl_bin())
        .args([
            "generate",
            "handler",
            "--template",
            fixture_path().to_str().unwrap(),
            "--language",
            "python",
            "--output",
            output_path.to_str().unwrap(),
        ])
        .output()
        .expect("Failed to execute tasker-ctl");

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let contents = std::fs::read_to_string(&output_path).unwrap();
    assert!(contents.contains("@step_handler(\"codegen_tests.validate_order\")"));
    assert!(contents.contains("def enrich_order("));
}
