{# Scaffold: TypeScript handlers with type imports and typed return values -#}
/** Generated by tasker-ctl generate scaffold. Handlers import generated types. */
import { defineHandler } from '@tasker-systems/tasker';
{% if !import_types.is_empty() -%}
import { {% for t in import_types %}{{ t }}{% if !loop.last %}, {% endif %}{% endfor %} } from './{{ types_module_name }}';
{% endif -%}
{% for handler in handlers %}

export const {{ handler.pascal_name() }} = defineHandler(
  '{{ handler.callable }}',
{%- if handler.has_dependencies() %}
  {
    depends: {
{%- for dep in handler.dependencies %}
      {{ dep.camel_param() }}: '{{ dep.step_name }}'{% if !loop.last %},{% endif %}
{%- endfor %}
    },
  },
  async ({ {% for dep in handler.dependencies %}{{ dep.camel_param() }}, {% endfor %}context }){% match handler.result_type_name() %}{% when Some with (type_name) %}: Promise<{{ type_name }}>{% when None %}{% endmatch %} => {
{%- else %}
  {},
  async ({ context }){% match handler.result_type_name() %}{% when Some with (type_name) %}: Promise<{{ type_name }}>{% when None %}{% endmatch %} => {
{%- endif %}
{%- for dep in handler.dependencies %}
    // {{ dep.camel_param() }}: {{ dep.type_comment() }}
{%- endfor %}
    // TODO: implement handler logic
{%- match handler.result_type_name() %}
{%- when Some with (type_name) %}
{%- match type_map.get(type_name.as_str()) %}
{%- when Some with (td) %}
    const result: {{ type_name }} = {
{%- for field in td.fields %}
      {{ field.name }}: {{ field.field_type.typescript_stub_value() }},
{%- endfor %}
    };
    return result;
{%- when None %}
    return {};
{%- endmatch %}
{%- when None %}
    return {};
{%- endmatch %}
  }
);
{%- endfor %}
