{# TAS-280: TypeScript test scaffold generation from task template -#}
/** Generated by tasker-ctl generate handler --with-tests. Customize to test your handlers. */
import { describe, test, expect } from 'bun:test';
{% for handler in handlers %}

describe('{{ handler.pascal_name() }}', () => {
{%- if handler.has_dependencies() %}
  test('processes with dependencies', async () => {
{%- for dep in handler.dependencies %}
{%- if dep.result_type.is_some() %}
    const mock{{ dep.pascal_param() }} = {
{%- for field in dep.stub_fields %}
      {{ field.name }}: {{ field.typescript_value() }},
{%- endfor %}
    };
{%- else %}
    const mock{{ dep.pascal_param() }} = {};
{%- endif %}
{%- endfor %}
    // TODO: create mock context and invoke handler
    expect(true).toBe(true); // placeholder
  });
{%- else %}
  test('returns expected result', async () => {
    // TODO: create mock context and invoke handler
    expect(true).toBe(true); // placeholder
  });
{%- endif %}
});
{%- endfor %}
