/**
 * FFI type definitions for TypeScript/JavaScript workers.
 *
 * TAS-290: These types are RE-EXPORTED from the napi-rs auto-generated
 * `index.d.ts` at the package root. The Rust `#[napi(object)]` structs
 * are the single source of truth — napi-rs generates TypeScript declarations
 * automatically, and this file re-exports them for use within `src/`.
 *
 * Types that we CONSTRUCT to send to Rust (NapiStepExecutionResult and its
 * children) have local interfaces with stricter nullability (`| null` instead
 * of `?:`) to work correctly with `exactOptionalPropertyTypes: true`.
 *
 * Types that only need `#napi-generated` must NOT be manually duplicated here.
 */

// =============================================================================
// Re-exports from napi-rs auto-generated index.d.ts
//
// These are the canonical types generated by `#[napi(object)]` in bridge.rs.
// The `#napi-generated` path alias is mapped in tsconfig.json to ./index.d.ts.
// =============================================================================

export type {
  BootstrapConfig,
  BootstrapResult,
  NapiCheckpointYieldData,
  NapiClientResult,
  NapiDependencyResult,
  NapiDispatchMetrics,
  NapiDomainEvent,
  NapiDomainEventMetadata,
  NapiListTasksParams,
  NapiStepDefinition,
  NapiStepEvent,
  NapiTaskInfo,
  NapiTaskRequest,
  NapiWorkflowStep,
  WorkerStatus,
} from '#napi-generated';

// =============================================================================
// Construction types — stricter than auto-generated for TypeScript callers
//
// napi-rs maps `Option<T>` to `?: T` (optional property). But when we
// explicitly construct these objects we set `null` (not `undefined`), which
// requires `T | null` typing with `exactOptionalPropertyTypes: true`.
//
// These are the ONLY types that need manual maintenance. They mirror:
//   workers/typescript/src-rust/bridge.rs :: NapiStepExecutionResult
//   workers/typescript/src-rust/bridge.rs :: NapiStepExecutionMetadata
//   workers/typescript/src-rust/bridge.rs :: NapiStepExecutionError
// =============================================================================

/**
 * Step execution result sent back to Rust from TypeScript handlers.
 *
 * Mirrors: bridge.rs `NapiStepExecutionResult` with `#[napi(object)]`.
 * Uses `| null` instead of `?:` because we explicitly construct these.
 */
export interface NapiStepExecutionResult {
  stepUuid: string;
  success: boolean;
  result: unknown;
  status: 'completed' | 'failed' | 'error';
  metadata: NapiStepExecutionMetadata;
  // napi-rs maps Option<T> to `?: T` — use undefined (omit) for None, not null
  error?: NapiStepExecutionError;
  orchestrationMetadata?: NapiOrchestrationMetadata;
}

export interface NapiStepExecutionMetadata {
  executionTimeMs: number;
  workerId?: string;
  completedAt: string;
  retryable?: boolean;
  errorType?: string;
  errorCode?: string;
  custom?: Record<string, unknown>;
}

export interface NapiStepExecutionError {
  message: string;
  errorType?: string;
  retryable?: boolean;
  statusCode?: number;
  backtrace?: string[];
  context?: Record<string, unknown>;
}

/**
 * Orchestration metadata for workflow coordination hints.
 *
 * Handlers can return this to influence orchestration decisions — e.g.,
 * passing Retry-After headers from external APIs, requesting explicit
 * backoff, or providing domain-specific routing hints.
 *
 * Matches: tasker_shared::messaging::message::OrchestrationMetadata
 */
export interface NapiOrchestrationMetadata {
  headers?: Record<string, string>;
  errorContext?: string | null;
  backoffHint?: NapiBackoffHint | null;
  custom?: Record<string, unknown>;
}

/**
 * Backoff hint from handler to orchestration system.
 *
 * Matches: tasker_shared::messaging::message::BackoffHint
 */
export interface NapiBackoffHint {
  backoffType: string;
  delaySeconds: number;
  context?: string | null;
}

// =============================================================================
// Compatibility Aliases
// =============================================================================

/** @deprecated Use NapiStepEvent directly */
export type FfiStepEvent = import('#napi-generated').NapiStepEvent;

/** @deprecated Use NapiDispatchMetrics directly */
export type FfiDispatchMetrics = import('#napi-generated').NapiDispatchMetrics;

/** @deprecated Use NapiDomainEvent directly */
export type FfiDomainEvent = import('#napi-generated').NapiDomainEvent;

/** @deprecated Use NapiDomainEventMetadata directly */
export type FfiDomainEventMetadata = import('#napi-generated').NapiDomainEventMetadata;

/** @deprecated Use NapiStepExecutionResult directly */
export type StepExecutionResult = NapiStepExecutionResult;

// =============================================================================
// Non-napi types (not generated by Rust)
// =============================================================================

/** Log fields for structured logging */
export interface LogFields {
  [key: string]: string | number | boolean | null;
}

/** Checkpoint yield data alias */
export type CheckpointYieldData = import('#napi-generated').NapiCheckpointYieldData;

/** Stop result alias */
export type StopResult = import('#napi-generated').WorkerStatus;
